### ISSUE TITLE
Technovation.org — Formatting Issues for posts

### ISSUE THREAD

**Issue by ghost** [Iridescent-CM/technovation-wp#96]
**Website:** Technovation.org 

**Problem:** Default image settings for images embedded into posts cause too much padding to display around images, and it is not possible to wrap text around images using the text editor. (We can only wrap text by editing the img style tag and using float and additional padding) 

**Ideal Solution:** It would be wonderful if an embedded image displayed on the published post in a way that allowed text to wrap around the image without having to manually edit the image style tag in html.   

**See the problem:** you can see an example of image formatting on the blog posts. Recommend creating a private blog post with lorem ipsum and trying to right align an embedded image to understand complication with embedded images.

**Comment by ghost** [comment]
@mjaris @rsgonzal I've fixed styles (on staging) for image displayed on the published post by added the 'post-img-left' (if the images on the left) or 'post-img-right' (if the images on the right) class in image tag.

Please take a look example post: https://techstage19.wpengine.com/blogs/test-post-images/

You can also compare the posts on staging & production for checking the padding to display around images:
Staging: https://techstage19.wpengine.com/blogs/climate-change-game/
Production: https://www.technovation.org/blogs/climate-change-game/

Please confirm if everything is working fine and we'll update styles for image on production.

PS: You can use the class 'post-img-left' or 'post-img-right' in images tag for new posts.

Thanks,

**Comment by jarism** [comment]
@thaopham-agilityio this looks good to me, thank you! Can you confirm when the changes are made on production? 

Thank you!

**Comment by ghost** [comment]
> Can you confirm when t

@rsgonzal I've updated code on production but it's not effective.
Please help to deploy code on production.

Thank you!

**Comment by jarism** [comment]
@thaopham-agilityio @rsgonzal deployed technovation.org this morning, although I'm not seeing the image tag in the sample blog posts. The test images look good, but I don't see the the class 'post-img-left' or 'post-img-right' in any of the images tags

- https://techstage19.wpengine.com/blogs/test-post-images/
- https://www.technovation.org/blogs/climate-change-game/

**Comment by ghost** [comment]
> @thaopham-agilityio @rsgonzal deployed technovation.org this morning, although I'm not seeing the image tag in the sample blog posts. The test images look good, but I don't see the the class 'post-img-left' or 'post-img-right' in any of the images tags
> 
> * https://techstage19.wpengine.com/blogs/test-post-images/
> * https://www.technovation.org/blogs/climate-change-game/

Hi @jarism, I've just fixed this one. Please double check. Thanks!

**Comment by jarism** [comment]
Hello! I'm still not seeing the image class tags, on either production or staging for the posts (images attached are where I'm looking for the tags in the posts—let me know if I should be looking somewhere else). 

<img width="1263" alt="Screen Shot 2021-05-12 at 10 07 50 AM" src="https://user-images.githubusercontent.com/33399908/117989092-06334400-b30a-11eb-97d1-a819e6ac6c1c.png">
<img width="1081" alt="Screen Shot 2021-05-12 at 10 07 20 AM" src="https://user-images.githubusercontent.com/33399908/117989097-06cbda80-b30a-11eb-9013-69134f8ea541.png">

**Comment by ghost** [comment]
@mjaris `Ideal Solution: It would be wonderful if an embedded image displayed on the published post in a way that allowed text to wrap around the image without having to manually edit the image style tag in html.`

I've used the Jquery (javascript) to check if the images (displayed on the published post) on the left or right, It will be auto added class 'post-img-left' or 'post-img-right' into image tags.

**Comment by rsgonzal** [comment]
Thank you, @thaopham-agilityio ! We are able to see the updates and are reviewing, we will let you know if there is any followup work.

**Comment by jarism** [comment]
Hi @thaopham-agilityio I am trying to test this out with a new blog post and am unfortunately still having the same issues. I tried using the "post-img-right" tag in the html, and then the "right align" button from the menu but am still not seeing it format properly. Should I be doing something different to get it to align?

- https://techstage19.wpengine.com/?post_type=blogs&p=20371&preview=true (it's a draft, so will have to login to see issue!)

**Comment by ghost** [comment]
Hi @jarism Maybe someone did a reverting. I have just updated snippet code. Please double check. Thanks for your patience.
